export type CatalogueExpansionItem = {
  slug: string;
  title: string;
  originalTitle: string;
  year: number;
  status: "ongoing" | "completed" | "announced";
  total: number | null;
  released: number;
  rating: number;
  genres: string[];
  age?: string;
  type?: "series" | "movie" | "ova" | "ona";
};

// Метаданные для расширенного демонстрационного каталога. Обложки для этих
// записей генерируются локально, чтобы не копировать сторонние постеры.
export const catalogueExpansion: CatalogueExpansionItem[] = [
  { slug: "naruto", title: "Наруто", originalTitle: "Naruto", year: 2002, status: "completed", total: 220, released: 220, rating: 8.2, genres: ["action", "adventure", "comedy"], age: "12+" },
  { slug: "naruto-shippuden", title: "Наруто: Ураганные хроники", originalTitle: "Naruto: Shippuden", year: 2007, status: "completed", total: 500, released: 500, rating: 8.6, genres: ["action", "adventure", "drama"], age: "12+" },
  { slug: "one-piece", title: "Ван-Пис", originalTitle: "One Piece", year: 1999, status: "ongoing", total: null, released: 1120, rating: 8.8, genres: ["action", "adventure", "comedy"], age: "12+" },
  { slug: "bleach", title: "Блич", originalTitle: "BLEACH", year: 2004, status: "completed", total: 366, released: 366, rating: 8.2, genres: ["action", "adventure", "supernatural"], age: "16+" },
  { slug: "fullmetal-alchemist-brotherhood", title: "Стальной алхимик: Братство", originalTitle: "Fullmetal Alchemist: Brotherhood", year: 2009, status: "completed", total: 64, released: 64, rating: 9.1, genres: ["action", "adventure", "drama", "fantasy"], age: "16+" },
  { slug: "death-note", title: "Тетрадь смерти", originalTitle: "Death Note", year: 2006, status: "completed", total: 37, released: 37, rating: 8.8, genres: ["drama", "mystery", "psychological", "thriller"], age: "16+" },
  { slug: "code-geass", title: "Код Гиас: Восставший Лелуш", originalTitle: "Code Geass: Hangyaku no Lelouch", year: 2006, status: "completed", total: 25, released: 25, rating: 8.7, genres: ["action", "drama", "mecha", "psychological"], age: "16+" },
  { slug: "cowboy-bebop", title: "Ковбой Бибоп", originalTitle: "Cowboy Bebop", year: 1998, status: "completed", total: 26, released: 26, rating: 8.7, genres: ["action", "adventure", "drama", "sci_fi"], age: "16+" },
  { slug: "neon-genesis-evangelion", title: "Евангелион", originalTitle: "Neon Genesis Evangelion", year: 1995, status: "completed", total: 26, released: 26, rating: 8.4, genres: ["action", "drama", "psychological", "sci_fi"], age: "16+" },
  { slug: "hunter-x-hunter-2011", title: "Охотник х Охотник", originalTitle: "Hunter x Hunter (2011)", year: 2011, status: "completed", total: 148, released: 148, rating: 9.0, genres: ["action", "adventure", "fantasy"], age: "12+" },
  { slug: "gintama", title: "Гинтама", originalTitle: "Gintama", year: 2006, status: "completed", total: 201, released: 201, rating: 8.9, genres: ["action", "comedy", "sci_fi"], age: "16+" },
  { slug: "jojos-bizarre-adventure", title: "Невероятные приключения ДжоДжо", originalTitle: "JoJo no Kimyou na Bouken", year: 2012, status: "completed", total: 26, released: 26, rating: 8.3, genres: ["action", "adventure", "supernatural"], age: "16+" },
  { slug: "black-clover", title: "Чёрный клевер", originalTitle: "Black Clover", year: 2017, status: "announced", total: null, released: 170, rating: 8.1, genres: ["action", "adventure", "fantasy"], age: "12+" },
  { slug: "my-hero-academia", title: "Моя геройская академия", originalTitle: "Boku no Hero Academia", year: 2016, status: "completed", total: 13, released: 13, rating: 7.9, genres: ["action", "comedy", "supernatural"], age: "12+" },
  { slug: "dr-stone", title: "Доктор Стоун", originalTitle: "Dr. STONE", year: 2019, status: "completed", total: 24, released: 24, rating: 8.2, genres: ["adventure", "comedy", "sci_fi"], age: "12+" },
  { slug: "fire-force", title: "Пламенная бригада пожарных", originalTitle: "Enen no Shouboutai", year: 2019, status: "ongoing", total: null, released: 48, rating: 7.8, genres: ["action", "drama", "supernatural"], age: "16+" },
  { slug: "mob-psycho-100", title: "Моб Психо 100", originalTitle: "Mob Psycho 100", year: 2016, status: "completed", total: 12, released: 12, rating: 8.6, genres: ["action", "comedy", "supernatural"], age: "12+" },
  { slug: "chainsaw-man", title: "Человек-бензопила", originalTitle: "Chainsaw Man", year: 2022, status: "ongoing", total: null, released: 12, rating: 8.4, genres: ["action", "horror", "supernatural"], age: "18+" },
  { slug: "hells-paradise", title: "Адский рай", originalTitle: "Jigokuraku", year: 2023, status: "ongoing", total: null, released: 13, rating: 8.0, genres: ["action", "adventure", "fantasy"], age: "18+" },
  { slug: "blue-lock", title: "Синяя тюрьма: Блю Лок", originalTitle: "Blue Lock", year: 2022, status: "ongoing", total: null, released: 38, rating: 8.0, genres: ["drama", "sports", "thriller"], age: "12+" },
  { slug: "kurokos-basketball", title: "Баскетбол Куроко", originalTitle: "Kuroko no Basket", year: 2012, status: "completed", total: 25, released: 25, rating: 7.9, genres: ["comedy", "sports"], age: "12+" },
  { slug: "slam-dunk", title: "Слэм-данк", originalTitle: "Slam Dunk", year: 1993, status: "completed", total: 101, released: 101, rating: 8.5, genres: ["comedy", "drama", "sports"], age: "12+" },
  { slug: "initial-d", title: "Инициал Ди", originalTitle: "Initial D", year: 1998, status: "completed", total: 26, released: 26, rating: 8.1, genres: ["action", "drama", "sports"], age: "12+" },
  { slug: "yuri-on-ice", title: "Юри на льду", originalTitle: "Yuri!!! on Ice", year: 2016, status: "completed", total: 12, released: 12, rating: 7.9, genres: ["drama", "romance", "sports"], age: "12+" },
  { slug: "banana-fish", title: "Банановая рыба", originalTitle: "Banana Fish", year: 2018, status: "completed", total: 24, released: 24, rating: 8.4, genres: ["action", "drama", "mystery"], age: "18+" },
  { slug: "fruits-basket-2019", title: "Корзинка фруктов", originalTitle: "Fruits Basket (2019)", year: 2019, status: "completed", total: 25, released: 25, rating: 8.2, genres: ["comedy", "drama", "romance", "supernatural"], age: "12+" },
  { slug: "toradora", title: "Торадора!", originalTitle: "Toradora!", year: 2008, status: "completed", total: 25, released: 25, rating: 8.1, genres: ["comedy", "drama", "romance"], age: "12+" },
  { slug: "your-lie-in-april", title: "Твоя апрельская ложь", originalTitle: "Shigatsu wa Kimi no Uso", year: 2014, status: "completed", total: 22, released: 22, rating: 8.6, genres: ["drama", "music", "romance"], age: "12+" },
  { slug: "clannad-after-story", title: "Кланнад: Продолжение истории", originalTitle: "Clannad: After Story", year: 2008, status: "completed", total: 24, released: 24, rating: 8.7, genres: ["drama", "romance", "slice_of_life"], age: "12+" },
  { slug: "rascal-does-not-dream", title: "Этот глупый свин не понимает мечту девочки-зайки", originalTitle: "Seishun Buta Yarou", year: 2018, status: "completed", total: 13, released: 13, rating: 8.0, genres: ["drama", "romance", "supernatural"], age: "12+" },
  { slug: "horimiya", title: "Хоримия", originalTitle: "Horimiya", year: 2021, status: "completed", total: 13, released: 13, rating: 7.9, genres: ["comedy", "romance", "slice_of_life"], age: "12+" },
  { slug: "my-dress-up-darling", title: "Эта фарфоровая кукла влюбилась", originalTitle: "Sono Bisque Doll wa Koi wo Suru", year: 2022, status: "ongoing", total: null, released: 24, rating: 7.9, genres: ["comedy", "romance", "slice_of_life"], age: "16+" },
  { slug: "komi-cant-communicate", title: "У Коми проблемы с общением", originalTitle: "Komi-san wa, Comyushou desu.", year: 2021, status: "completed", total: 12, released: 12, rating: 7.7, genres: ["comedy", "romance", "slice_of_life"], age: "12+" },
  { slug: "wotakoi", title: "Так сложно любить отаку", originalTitle: "Wotaku ni Koi wa Muzukashii", year: 2018, status: "completed", total: 11, released: 11, rating: 7.8, genres: ["comedy", "romance", "slice_of_life"], age: "12+" },
  { slug: "lovely-complex", title: "Трогательный комплекс", originalTitle: "Lovely★Complex", year: 2007, status: "completed", total: 24, released: 24, rating: 7.8, genres: ["comedy", "romance"], age: "12+" },
  { slug: "orange", title: "Оранжевый", originalTitle: "Orange", year: 2016, status: "completed", total: 13, released: 13, rating: 7.6, genres: ["drama", "romance", "sci_fi"], age: "12+" },
  { slug: "a-silent-voice", title: "Форма голоса", originalTitle: "Koe no Katachi", year: 2016, status: "completed", total: 1, released: 1, rating: 8.8, genres: ["drama", "romance"], age: "12+", type: "movie" },
  { slug: "your-name", title: "Твоё имя", originalTitle: "Kimi no Na wa.", year: 2016, status: "completed", total: 1, released: 1, rating: 8.7, genres: ["drama", "romance", "supernatural"], age: "12+", type: "movie" },
  { slug: "weathering-with-you", title: "Дитя погоды", originalTitle: "Tenki no Ko", year: 2019, status: "completed", total: 1, released: 1, rating: 8.1, genres: ["drama", "romance", "supernatural"], age: "12+", type: "movie" },
  { slug: "suzume", title: "Судзумэ, закрывающая двери", originalTitle: "Suzume no Tojimari", year: 2022, status: "completed", total: 1, released: 1, rating: 8.0, genres: ["adventure", "drama", "fantasy"], age: "12+", type: "movie" },
  { slug: "princess-mononoke", title: "Принцесса Мононоке", originalTitle: "Mononoke Hime", year: 1997, status: "completed", total: 1, released: 1, rating: 8.7, genres: ["adventure", "drama", "fantasy"], age: "12+", type: "movie" },
  { slug: "howls-moving-castle", title: "Ходячий замок", originalTitle: "Howl no Ugoku Shiro", year: 2004, status: "completed", total: 1, released: 1, rating: 8.5, genres: ["adventure", "fantasy", "romance"], age: "6+", type: "movie" },
  { slug: "my-neighbor-totoro", title: "Мой сосед Тоторо", originalTitle: "Tonari no Totoro", year: 1988, status: "completed", total: 1, released: 1, rating: 8.4, genres: ["adventure", "fantasy", "slice_of_life"], age: "6+", type: "movie" },
  { slug: "grave-of-the-fireflies", title: "Могила светлячков", originalTitle: "Hotaru no Haka", year: 1988, status: "completed", total: 1, released: 1, rating: 8.5, genres: ["drama"], age: "16+", type: "movie" },
  { slug: "kikis-delivery-service", title: "Ведьмина служба доставки", originalTitle: "Majo no Takkyuubin", year: 1989, status: "completed", total: 1, released: 1, rating: 8.1, genres: ["adventure", "fantasy"], age: "6+", type: "movie" },
  { slug: "ponyo", title: "Рыбка Поньо на утёсе", originalTitle: "Gake no Ue no Ponyo", year: 2008, status: "completed", total: 1, released: 1, rating: 7.8, genres: ["adventure", "fantasy"], age: "6+", type: "movie" },
  { slug: "the-boy-and-the-heron", title: "Мальчик и птица", originalTitle: "Kimitachi wa Dou Ikiru ka", year: 2023, status: "completed", total: 1, released: 1, rating: 7.8, genres: ["adventure", "drama", "fantasy"], age: "12+", type: "movie" },
  { slug: "perfect-blue", title: "Истинная грусть", originalTitle: "Perfect Blue", year: 1997, status: "completed", total: 1, released: 1, rating: 8.4, genres: ["drama", "horror", "psychological", "thriller"], age: "18+", type: "movie" },
  { slug: "paprika", title: "Паприка", originalTitle: "Paprika", year: 2006, status: "completed", total: 1, released: 1, rating: 8.1, genres: ["mystery", "psychological", "sci_fi"], age: "16+", type: "movie" },
  { slug: "millennium-actress", title: "Актриса тысячелетия", originalTitle: "Sennen Joyuu", year: 2001, status: "completed", total: 1, released: 1, rating: 8.1, genres: ["drama", "romance"], age: "12+", type: "movie" },
  { slug: "tokyo-godfathers", title: "Однажды в Токио", originalTitle: "Tokyo Godfathers", year: 2003, status: "completed", total: 1, released: 1, rating: 8.1, genres: ["comedy", "drama"], age: "12+", type: "movie" },
  { slug: "akira", title: "Акира", originalTitle: "AKIRA", year: 1988, status: "completed", total: 1, released: 1, rating: 8.1, genres: ["action", "psychological", "sci_fi"], age: "18+", type: "movie" },
  { slug: "ghost-in-the-shell", title: "Призрак в доспехах", originalTitle: "Koukaku Kidoutai", year: 1995, status: "completed", total: 1, released: 1, rating: 8.2, genres: ["action", "mystery", "sci_fi"], age: "16+", type: "movie" },
  { slug: "redline", title: "Красная черта", originalTitle: "REDLINE", year: 2009, status: "completed", total: 1, released: 1, rating: 7.9, genres: ["action", "sci_fi", "sports"], age: "16+", type: "movie" },
  { slug: "promare", title: "Промар", originalTitle: "Promare", year: 2019, status: "completed", total: 1, released: 1, rating: 7.7, genres: ["action", "fantasy", "sci_fi"], age: "12+", type: "movie" },
  { slug: "kill-la-kill", title: "Убей или умри", originalTitle: "Kill la Kill", year: 2013, status: "completed", total: 24, released: 24, rating: 8.0, genres: ["action", "comedy", "fantasy"], age: "16+" },
  { slug: "gurren-lagann", title: "Гуррен-Лаганн", originalTitle: "Tengen Toppa Gurren Lagann", year: 2007, status: "completed", total: 27, released: 27, rating: 8.6, genres: ["action", "adventure", "sci_fi"], age: "12+" },
  { slug: "flcl", title: "Фури-Кури", originalTitle: "FLCL", year: 2000, status: "completed", total: 6, released: 6, rating: 8.0, genres: ["comedy", "psychological", "sci_fi"], age: "16+", type: "ova" },
  { slug: "made-in-abyss", title: "Созданный в Бездне", originalTitle: "Made in Abyss", year: 2017, status: "ongoing", total: null, released: 13, rating: 8.7, genres: ["adventure", "drama", "fantasy", "mystery"], age: "16+" },
  { slug: "land-of-the-lustrous", title: "Страна самоцветов", originalTitle: "Houseki no Kuni", year: 2017, status: "announced", total: null, released: 12, rating: 8.4, genres: ["action", "drama", "fantasy", "mystery"], age: "12+" },
  { slug: "violet-evergarden", title: "Вайолет Эвергарден", originalTitle: "Violet Evergarden", year: 2018, status: "completed", total: 13, released: 13, rating: 8.5, genres: ["drama", "fantasy", "slice_of_life"], age: "12+" },
  { slug: "eighty-six", title: "Восемьдесят шесть", originalTitle: "86", year: 2021, status: "completed", total: 23, released: 23, rating: 8.4, genres: ["action", "drama", "sci_fi"], age: "16+" },
  { slug: "re-zero", title: "Жизнь с нуля в альтернативном мире", originalTitle: "Re:Zero kara Hajimeru Isekai Seikatsu", year: 2016, status: "ongoing", total: null, released: 66, rating: 8.2, genres: ["drama", "fantasy", "psychological", "thriller"], age: "16+" },
  { slug: "mushoku-tensei", title: "Реинкарнация безработного", originalTitle: "Mushoku Tensei", year: 2021, status: "ongoing", total: null, released: 48, rating: 8.3, genres: ["adventure", "drama", "fantasy"], age: "16+" },
  { slug: "konosuba", title: "Этот замечательный мир!", originalTitle: "Kono Subarashii Sekai ni Shukufuku wo!", year: 2016, status: "ongoing", total: null, released: 31, rating: 8.0, genres: ["adventure", "comedy", "fantasy"], age: "12+" },
  { slug: "overlord", title: "Повелитель", originalTitle: "Overlord", year: 2015, status: "ongoing", total: null, released: 52, rating: 7.9, genres: ["action", "adventure", "fantasy"], age: "16+" },
  { slug: "that-time-i-got-reincarnated", title: "О моём перерождении в слизь", originalTitle: "Tensei shitara Slime Datta Ken", year: 2018, status: "ongoing", total: null, released: 72, rating: 8.0, genres: ["adventure", "comedy", "fantasy"], age: "12+" },
  { slug: "log-horizon", title: "Лог Горизонт", originalTitle: "Log Horizon", year: 2013, status: "completed", total: 25, released: 25, rating: 7.8, genres: ["adventure", "fantasy", "sci_fi"], age: "12+" },
  { slug: "no-game-no-life", title: "Нет игры — нет жизни", originalTitle: "No Game No Life", year: 2014, status: "announced", total: null, released: 12, rating: 7.9, genres: ["adventure", "comedy", "fantasy"], age: "12+" },
  { slug: "sword-art-online", title: "Мастера меча онлайн", originalTitle: "Sword Art Online", year: 2012, status: "completed", total: 25, released: 25, rating: 7.5, genres: ["action", "adventure", "fantasy", "romance"], age: "12+" },
  { slug: "fate-zero", title: "Судьба: Начало", originalTitle: "Fate/Zero", year: 2011, status: "completed", total: 13, released: 13, rating: 8.4, genres: ["action", "drama", "fantasy"], age: "16+" },
  { slug: "fate-stay-night-ubw", title: "Судьба: Ночь схватки — Бесконечный мир клинков", originalTitle: "Fate/stay night: Unlimited Blade Works", year: 2014, status: "completed", total: 12, released: 12, rating: 8.0, genres: ["action", "fantasy", "supernatural"], age: "16+" },
  { slug: "fate-stay-night-heavens-feel", title: "Судьба: Ночь схватки — Прикосновение небес", originalTitle: "Fate/stay night: Heaven's Feel", year: 2017, status: "completed", total: 1, released: 1, rating: 8.3, genres: ["action", "fantasy", "supernatural"], age: "16+", type: "movie" },
  { slug: "fate-apocrypha", title: "Судьба: Апокриф", originalTitle: "Fate/Apocrypha", year: 2017, status: "completed", total: 25, released: 25, rating: 7.4, genres: ["action", "fantasy", "supernatural"], age: "16+" },
  { slug: "bakemonogatari", title: "Истории монстров", originalTitle: "Bakemonogatari", year: 2009, status: "completed", total: 15, released: 15, rating: 8.3, genres: ["mystery", "romance", "supernatural"], age: "16+" },
  { slug: "the-melancholy-of-haruhi-suzumiya", title: "Меланхолия Харухи Судзумии", originalTitle: "Suzumiya Haruhi no Yuuutsu", year: 2006, status: "completed", total: 14, released: 14, rating: 7.8, genres: ["comedy", "sci_fi", "slice_of_life"], age: "12+" },
  { slug: "k-on", title: "Кэйон!", originalTitle: "K-ON!", year: 2009, status: "completed", total: 13, released: 13, rating: 8.1, genres: ["comedy", "music", "slice_of_life"], age: "12+" },
  { slug: "nichijou", title: "Будни старшеклассников", originalTitle: "Nichijou", year: 2011, status: "completed", total: 26, released: 26, rating: 8.2, genres: ["comedy", "slice_of_life"], age: "12+" },
  { slug: "azumanga-daioh", title: "Адзуманга Дайо", originalTitle: "Azumanga Daioh", year: 2002, status: "completed", total: 26, released: 26, rating: 7.8, genres: ["comedy", "slice_of_life"], age: "12+" },
  { slug: "yuru-camp", title: "Лагерь на свежем воздухе", originalTitle: "Yuru Camp△", year: 2018, status: "ongoing", total: null, released: 37, rating: 8.1, genres: ["comedy", "slice_of_life"], age: "6+" },
  { slug: "non-non-biyori", title: "Деревенская глубинка", originalTitle: "Non Non Biyori", year: 2013, status: "completed", total: 12, released: 12, rating: 8.0, genres: ["comedy", "slice_of_life"], age: "6+" },
  { slug: "barakamon", title: "Баракамон", originalTitle: "Barakamon", year: 2014, status: "completed", total: 12, released: 12, rating: 8.2, genres: ["comedy", "slice_of_life"], age: "6+" },
  { slug: "march-comes-in-like-a-lion", title: "Мартовский лев", originalTitle: "3-gatsu no Lion", year: 2016, status: "completed", total: 22, released: 22, rating: 8.5, genres: ["drama", "slice_of_life"], age: "12+" },
  { slug: "showa-genroku-rakugo", title: "Эпоха Сёва: Истории ракуго", originalTitle: "Shouwa Genroku Rakugo Shinjuu", year: 2016, status: "completed", total: 13, released: 13, rating: 8.6, genres: ["drama"], age: "16+" },
  { slug: "chihayafuru", title: "Яркая Тихая", originalTitle: "Chihayafuru", year: 2011, status: "completed", total: 25, released: 25, rating: 8.2, genres: ["drama", "romance", "sports"], age: "12+" },
  { slug: "ping-pong-the-animation", title: "Пинг-понг", originalTitle: "Ping Pong the Animation", year: 2014, status: "completed", total: 11, released: 11, rating: 8.6, genres: ["drama", "psychological", "sports"], age: "12+" },
  { slug: "hajime-no-ippo", title: "Первый шаг", originalTitle: "Hajime no Ippo", year: 2000, status: "completed", total: 75, released: 75, rating: 8.7, genres: ["comedy", "drama", "sports"], age: "12+" },
  { slug: "megalo-box", title: "Мегалобокс", originalTitle: "Megalo Box", year: 2018, status: "completed", total: 13, released: 13, rating: 7.8, genres: ["action", "drama", "sci_fi", "sports"], age: "12+" },
  { slug: "run-with-the-wind", title: "Почувствуй ветер", originalTitle: "Kaze ga Tsuyoku Fuiteiru", year: 2018, status: "completed", total: 23, released: 23, rating: 8.4, genres: ["drama", "sports"], age: "12+" },
  { slug: "tsurune", title: "Цурунэ: Клуб стрельбы из лука", originalTitle: "Tsurune", year: 2018, status: "completed", total: 13, released: 13, rating: 7.6, genres: ["drama", "sports"], age: "12+" },
  { slug: "free-iwatobi-swim-club", title: "Вольный стиль!", originalTitle: "Free!", year: 2013, status: "completed", total: 12, released: 12, rating: 7.5, genres: ["comedy", "sports"], age: "12+" },
  { slug: "sk8-the-infinity", title: "Скейт: Бесконечность", originalTitle: "SK∞", year: 2021, status: "completed", total: 12, released: 12, rating: 7.7, genres: ["action", "sports"], age: "12+" },
  { slug: "bungou-stray-dogs", title: "Великий из бродячих псов", originalTitle: "Bungou Stray Dogs", year: 2016, status: "ongoing", total: null, released: 61, rating: 8.0, genres: ["action", "mystery", "supernatural"], age: "16+" },
  { slug: "durarara", title: "Дюрарара!!", originalTitle: "Durarara!!", year: 2010, status: "completed", total: 24, released: 24, rating: 7.9, genres: ["action", "mystery", "supernatural"], age: "16+" },
  { slug: "baccano", title: "Шумиха!", originalTitle: "Baccano!", year: 2007, status: "completed", total: 13, released: 13, rating: 8.2, genres: ["action", "mystery", "supernatural"], age: "16+" },
  { slug: "black-lagoon", title: "Чёрная лагуна", originalTitle: "Black Lagoon", year: 2006, status: "completed", total: 12, released: 12, rating: 7.9, genres: ["action", "drama", "thriller"], age: "18+" },
  { slug: "hellsing-ultimate", title: "Хеллсинг: Война с нечистью", originalTitle: "Hellsing Ultimate", year: 2006, status: "completed", total: 10, released: 10, rating: 8.2, genres: ["action", "horror", "supernatural"], age: "18+", type: "ova" },
  { slug: "trigun-stampede", title: "Триган: Ураган", originalTitle: "Trigun Stampede", year: 2023, status: "announced", total: null, released: 12, rating: 7.7, genres: ["action", "adventure", "sci_fi"], age: "12+" },
  { slug: "samurai-champloo", title: "Самурай Чамплу", originalTitle: "Samurai Champloo", year: 2004, status: "completed", total: 26, released: 26, rating: 8.5, genres: ["action", "adventure", "drama"], age: "16+" },
  { slug: "rurouni-kenshin", title: "Бродяга Кэнсин", originalTitle: "Rurouni Kenshin: Meiji Kenkaku Romantan", year: 1996, status: "completed", total: 94, released: 94, rating: 8.2, genres: ["action", "adventure", "drama"], age: "12+" },
  { slug: "inuyasha", title: "Инуяша", originalTitle: "InuYasha", year: 2000, status: "completed", total: 167, released: 167, rating: 7.9, genres: ["action", "adventure", "fantasy", "romance"], age: "12+" },
  { slug: "yu-yu-hakusho", title: "Отчёт о буйстве духов", originalTitle: "Yuu☆Yuu☆Hakusho", year: 1992, status: "completed", total: 112, released: 112, rating: 8.5, genres: ["action", "adventure", "supernatural"], age: "12+" },
  { slug: "saint-seiya", title: "Рыцари Зодиака", originalTitle: "Saint Seiya", year: 1986, status: "completed", total: 114, released: 114, rating: 7.7, genres: ["action", "adventure", "fantasy"], age: "12+" },
  { slug: "sailor-moon", title: "Красавица-воин Сейлор Мун", originalTitle: "Bishoujo Senshi Sailor Moon", year: 1992, status: "completed", total: 46, released: 46, rating: 7.8, genres: ["action", "comedy", "romance", "supernatural"], age: "6+" },
  { slug: "cardcaptor-sakura", title: "Сакура — собирательница карт", originalTitle: "Cardcaptor Sakura", year: 1998, status: "completed", total: 70, released: 70, rating: 8.1, genres: ["adventure", "comedy", "fantasy", "romance"], age: "6+" },
  { slug: "puella-magi-madoka-magica", title: "Девочка-волшебница Мадока", originalTitle: "Mahou Shoujo Madoka★Magica", year: 2011, status: "completed", total: 12, released: 12, rating: 8.4, genres: ["drama", "fantasy", "psychological", "thriller"], age: "16+" },
  { slug: "revolutionary-girl-utena", title: "Юная революционерка Утэна", originalTitle: "Shoujo Kakumei Utena", year: 1997, status: "completed", total: 39, released: 39, rating: 8.1, genres: ["drama", "psychological", "romance"], age: "16+" },
  { slug: "serial-experiments-lain", title: "Эксперименты Лэйн", originalTitle: "Serial Experiments Lain", year: 1998, status: "completed", total: 13, released: 13, rating: 8.1, genres: ["mystery", "psychological", "sci_fi"], age: "16+" },
  { slug: "paranoia-agent", title: "Агент паранойи", originalTitle: "Mousou Dairinin", year: 2004, status: "completed", total: 13, released: 13, rating: 7.8, genres: ["mystery", "psychological", "thriller"], age: "16+" },
  { slug: "monster", title: "Монстр", originalTitle: "MONSTER", year: 2004, status: "completed", total: 74, released: 74, rating: 8.8, genres: ["drama", "mystery", "psychological", "thriller"], age: "18+" },
  { slug: "pluto", title: "Плутон", originalTitle: "PLUTO", year: 2023, status: "completed", total: 8, released: 8, rating: 8.4, genres: ["drama", "mystery", "psychological", "sci_fi"], age: "16+", type: "ona" },
  { slug: "odd-taxi", title: "Необычное такси", originalTitle: "Odd Taxi", year: 2021, status: "completed", total: 13, released: 13, rating: 8.4, genres: ["drama", "mystery", "psychological"], age: "16+" },
  { slug: "erased", title: "Город, в котором меня нет", originalTitle: "Boku dake ga Inai Machi", year: 2016, status: "completed", total: 12, released: 12, rating: 8.1, genres: ["drama", "mystery", "supernatural", "thriller"], age: "16+" },
  { slug: "psycho-pass", title: "Психопаспорт", originalTitle: "PSYCHO-PASS", year: 2012, status: "completed", total: 22, released: 22, rating: 8.3, genres: ["action", "mystery", "psychological", "sci_fi"], age: "16+" },
  { slug: "terror-in-resonance", title: "Террор в резонансе", originalTitle: "Zankyou no Terror", year: 2014, status: "completed", total: 11, released: 11, rating: 7.8, genres: ["mystery", "psychological", "thriller"], age: "16+" },
  { slug: "the-promised-neverland", title: "Обещанный Неверленд", originalTitle: "Yakusoku no Neverland", year: 2019, status: "completed", total: 12, released: 12, rating: 8.2, genres: ["drama", "mystery", "psychological", "thriller"], age: "16+" },
  { slug: "parasyte-the-maxim", title: "Паразит: Учение о жизни", originalTitle: "Kiseijuu: Sei no Kakuritsu", year: 2014, status: "completed", total: 24, released: 24, rating: 8.3, genres: ["action", "horror", "psychological", "sci_fi"], age: "18+" },
  { slug: "tokyo-ghoul", title: "Токийский гуль", originalTitle: "Tokyo Ghoul", year: 2014, status: "completed", total: 12, released: 12, rating: 7.6, genres: ["action", "horror", "supernatural"], age: "18+" },
  { slug: "devilman-crybaby", title: "Человек-дьявол: Плакса", originalTitle: "Devilman: Crybaby", year: 2018, status: "completed", total: 10, released: 10, rating: 7.8, genres: ["action", "horror", "psychological", "supernatural"], age: "18+", type: "ona" },
  { slug: "dorohedoro", title: "Дорохедоро", originalTitle: "Dorohedoro", year: 2020, status: "announced", total: null, released: 12, rating: 8.1, genres: ["action", "comedy", "fantasy", "horror"], age: "18+" },
  { slug: "beastars", title: "Выдающиеся звери", originalTitle: "BEASTARS", year: 2019, status: "completed", total: 12, released: 12, rating: 7.7, genres: ["drama", "psychological", "romance"], age: "16+" },
  { slug: "bna", title: "Совершенно новый зверь", originalTitle: "BNA", year: 2020, status: "completed", total: 12, released: 12, rating: 7.4, genres: ["action", "fantasy"], age: "12+" },
  { slug: "a-place-further-than-the-universe", title: "Место дальше вселенной", originalTitle: "Sora yori mo Tooi Basho", year: 2018, status: "completed", total: 13, released: 13, rating: 8.3, genres: ["adventure", "comedy", "drama"], age: "12+" },
  { slug: "summertime-render", title: "Летнее время", originalTitle: "Summertime Render", year: 2022, status: "completed", total: 25, released: 25, rating: 8.2, genres: ["mystery", "supernatural", "thriller"], age: "16+" },
  { slug: "keep-your-hands-off-eizouken", title: "Руки прочь от кинокружка!", originalTitle: "Eizouken ni wa Te wo Dasu na!", year: 2020, status: "completed", total: 12, released: 12, rating: 8.1, genres: ["comedy", "slice_of_life"], age: "12+" },
  { slug: "skip-and-loafer", title: "Безоблачное завтра", originalTitle: "Skip to Loafer", year: 2023, status: "ongoing", total: null, released: 12, rating: 8.0, genres: ["comedy", "romance", "slice_of_life"], age: "12+" },
];
